services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_reto7
    environment:
      SA_PASSWORD: "RETO7CONTRASEÃ‘A123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1437:1433"
    volumes:
      - sql_data_reto7:/var/opt/mssql

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_financial_lab
    ports:
      - "8897:8888"
    volumes:
      - ../:/home/jovyan/work
    depends_on:
      - sqlserver

volumes:
  sql_data_reto7:
